version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - mv build/libs/accompaniment-service-0.0.1-SNAPSHOT.jar accompaniment-service.jar
artifacts:
  files:
    - accompaniment-service.jar