version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - ./gradlew build
artifacts:
  files:
    - build/libs/accompaniment-service-0.0.1-SNAPSHOT.jar